//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2RLS.Pages.User
{
    public partial class LessonView
    {
        protected global::System.Web.UI.WebControls.Literal litCategoryBadge;
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.Literal litProgressPercent;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl progressBar;
        protected global::System.Web.UI.WebControls.Literal litContent;
        protected global::System.Web.UI.WebControls.Literal litTakeaways;
        protected global::System.Web.UI.WebControls.PlaceHolder phNextLesson;
        protected global::System.Web.UI.WebControls.Literal litNextLessonTitle;
        protected global::System.Web.UI.WebControls.PlaceHolder phQuote;
        protected global::System.Web.UI.WebControls.Literal litQuoteText;
        protected global::System.Web.UI.WebControls.Literal litQuoteAuthor;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkPrev;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkTakeQuiz;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkBackToList;
    }
}
