//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2RLS.Pages.User
{
    public partial class QuizResult
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlIcon;
        protected global::System.Web.UI.WebControls.Literal litIcon;
        protected global::System.Web.UI.WebControls.Literal litStatusTitle;
        protected global::System.Web.UI.WebControls.Literal litStatusSubtitle;
        protected global::System.Web.UI.WebControls.Literal litAchievements;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl scoreWrapper;
        protected global::System.Web.UI.WebControls.Literal litScore;
        protected global::System.Web.UI.WebControls.Literal litCorrect;
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Literal litCoins;
        protected global::System.Web.UI.WebControls.Literal litLevel;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkNextLesson;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkRetake;
    }
}
