//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2RLS
{


    public partial class _Default
    {

        /// <summary>phGuestCta control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phGuestCta;

        /// <summary>phMemberCta control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phMemberCta;

        /// <summary>phGuestCta2 control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phGuestCta2;

        /// <summary>phMemberCta2 control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phMemberCta2;
    }
}
