//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2RLS.Pages.Admin
{
    public partial class LessonCategoryEdit
    {
        protected global::System.Web.UI.WebControls.Literal litHeading;
        protected global::System.Web.UI.WebControls.ValidationSummary valSummary;
        protected global::System.Web.UI.WebControls.TextBox txtName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvName;
        protected global::System.Web.UI.WebControls.TextBox txtLevelNumber;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLevel;
        protected global::System.Web.UI.WebControls.RangeValidator rvLevel;
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        protected global::System.Web.UI.WebControls.TextBox txtEstimatedTime;
        protected global::System.Web.UI.WebControls.PlaceHolder phExistingImage;
        protected global::System.Web.UI.WebControls.Image imgPreview;
        protected global::System.Web.UI.WebControls.FileUpload fuImage;
        protected global::System.Web.UI.WebControls.TextBox txtImageUrl;
        protected global::System.Web.UI.WebControls.HiddenField hdnId;
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
