//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2RLS.Pages.Admin
{
    public partial class QuizQuestionEdit
    {
        /// <summary>litError control.</summary>
        protected global::System.Web.UI.WebControls.Literal litError;

        /// <summary>ddlLesson control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlLesson;

        /// <summary>hdnQuestionsJson control.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnQuestionsJson;

        /// <summary>btnSave control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>litExistingJson control.</summary>
        protected global::System.Web.UI.WebControls.Literal litExistingJson;
    }
}
