//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2RLS.Pages.Admin
{
    public partial class RewardItemEdit
    {
        protected global::System.Web.UI.WebControls.Literal litHeading;
        protected global::System.Web.UI.WebControls.Literal litAlert;
        protected global::System.Web.UI.WebControls.ValidationSummary valSummary;
        protected global::System.Web.UI.WebControls.TextBox txtName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvName;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
        protected global::System.Web.UI.WebControls.TextBox txtCost;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCost;
        protected global::System.Web.UI.WebControls.RangeValidator rvCost;
        protected global::System.Web.UI.WebControls.TextBox txtType;
        protected global::System.Web.UI.WebControls.FileUpload fuAssetImage;
        protected global::System.Web.UI.WebControls.PlaceHolder phPreview;
        protected global::System.Web.UI.WebControls.Image imgPreview;
        protected global::System.Web.UI.WebControls.HiddenField hdnId;
        protected global::System.Web.UI.WebControls.HiddenField hdnExistingImageUrl;
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}

